logging:
  path: /tmp/logs/template
  
spring:
 datasource:
   #url: jdbc:h2:~/.h2/template;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   url: jdbc:h2:mem:template;DB_CLOSE_DELAY=-1  #just demo
   platform: h2
   username: sa
   password:
   driverClassName: org.h2.Driver
   data: classpath:h2data/data.sql
 jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       show_sql: true
       use_sql_comments: true
       format_sql: true
 h2:
   console:
     enabled: true
     settings:
       trace: false
       web-allow-others: true